[package]
name = "fast_file_explorer"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.27"  # For terminal-based UI
walkdir = "2.4"  # For fast directory traversal
rayon = "1.8"  # For parallel processing